import type { ReactNode } from "react";

import { ArrowUpRightIcon, ChevronDownIcon } from "@/components/ui/icons";
import { Identifier } from "@/components/ui/identifier";
import { Kicker } from "@/components/ui/kicker";
import { Ledger, LedgerRow } from "@/components/ui/ledger";
import { Section } from "@/components/ui/section";
import { SectionHeading } from "@/components/ui/section-heading";
import { StatusBadge } from "@/components/ui/status-badge";
import { demo, freeze } from "@/lib/demo";
import { formatBytes, formatIndex, formatUtc, shortHash, shortId } from "@/lib/format";
import { demoFile, freezeFile, integrity, type InspectedFile } from "@/lib/integrity";
import { site } from "@/lib/site";

type ArtifactFileCardProps = {
  file: InspectedFile;
  title: string;
  description: string;
  badge?: ReactNode;
  children?: ReactNode;
};

function ArtifactFileCard({ file, title, description, badge, children }: ArtifactFileCardProps) {
  return (
    <article
      aria-label={`${title}: ${file.fileName}`}
      className="flex flex-col rounded-md border border-line bg-surface shadow-card"
    >
      <div className="flex items-start justify-between gap-4 p-5 sm:p-6">
        <div className="min-w-0">
          <Kicker>{title}</Kicker>
          <h3 className="mt-2 break-all font-mono text-base font-medium text-ink">{file.fileName}</h3>
          <p className="mt-2 text-sm leading-relaxed text-muted">{description}</p>
        </div>
        {badge}
      </div>

      <Ledger className="border-t border-line px-5 sm:px-6">
        <LedgerRow label="Published at">
          <Identifier value={file.publicPath} label="published path" variant="plain" copy={false} />
        </LedgerRow>
        <LedgerRow label="Size">
          {formatBytes(file.bytes)} <span className="text-faint">· {file.newline.toUpperCase()} newlines</span>
        </LedgerRow>
        <LedgerRow label="SHA-256">
          <Identifier variant="hash" value={file.sha256} label={`${file.fileName} SHA-256`} />
        </LedgerRow>
        {children}
      </Ledger>

      <div className="mt-auto flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-line px-5 py-3 text-sm sm:px-6">
        <a
          href={file.publicPath}
          className="inline-flex items-center gap-1 rounded-xs font-medium text-accent transition-colors hover:text-accent-strong"
        >
          Open raw file
          <ArrowUpRightIcon size={13} />
        </a>
        <a
          href={file.publicPath}
          download={file.fileName}
          className="rounded-xs font-medium text-accent transition-colors hover:text-accent-strong"
        >
          Download
        </a>
        <span className="ml-auto font-mono text-xs text-faint">{file.publicPath}</span>
      </div>
    </article>
  );
}

type ProvenanceEvent = {
  title: string;
  at: string;
  field: string;
  detail: ReactNode;
};

/**
 * Separates the export time of the evaluation record from the times the
 * manifest was generated and later corrected, so a digest correction
 * cannot read as a re-run of the evaluation.
 */
function ProvenanceTimeline() {
  const events: ProvenanceEvent[] = [
    {
      title: "Evaluation record exported",
      at: freeze.artifact_created_at,
      field: "artifact_created_at",
      detail: (
        <>
          The engine exported run{" "}
          <Identifier value={demo.run_id} display={shortId(demo.run_id)} label="run ID" copy={false} /> with
          its outcomes and evidence. This is the record&rsquo;s own <code className="text-hash text-[0.75rem]">created_at</code>.
        </>
      ),
    },
    {
      title: "Manifest generated by the engine",
      at: freeze.manifest_generated_at,
      field: "manifest_generated_at",
      detail: freeze.correction?.previous_demo_json_sha256 ? (
        <>
          Original digest, computed over a {freeze.correction.previous_demo_json_newline?.toUpperCase() ?? "different"}{" "}
          export of the same content:{" "}
          <Identifier
            value={freeze.correction.previous_demo_json_sha256}
            display={shortHash(freeze.correction.previous_demo_json_sha256)}
            label="superseded digest"
          />
        </>
      ) : (
        "The freeze manifest was written alongside the record."
      ),
    },
  ];

  if (freeze.manifest_corrected_at && freeze.correction) {
    events.push({
      title: "Manifest digest corrected",
      at: freeze.manifest_corrected_at,
      field: "manifest_corrected_at",
      detail: (
        <>
          Only manifest fields changed; the record was not re-run or edited. Digest recomputed over the
          canonical LF bytes:{" "}
          <Identifier
            value={freeze.demo_json_sha256}
            display={shortHash(freeze.demo_json_sha256)}
            label="current digest"
          />
        </>
      ),
    });
  }

  return (
    <div className="mt-6 rounded-md border border-line bg-surface p-5 shadow-card sm:p-6 lg:p-8">
      <div className="grid gap-6 lg:grid-cols-12 lg:gap-10">
        <div className="lg:col-span-4">
          <Kicker>Provenance</Kicker>
          <h3 className="mt-3 text-lg font-semibold leading-snug tracking-tight text-ink">
            The evaluation was not recomputed.
          </h3>
          <p className="mt-3 text-sm leading-relaxed text-muted">
            Three timestamps are kept apart on purpose: when the record was exported, when the engine
            generated the manifest, and when the published digest was corrected after newline
            normalization. The outcomes, identifiers and evidence date from the first.
          </p>
          {freeze.correction && (
            <p className="mt-3 text-xs leading-5 text-muted">
              <span className="font-mono text-faint">correction.reason</span> — {freeze.correction.reason}
            </p>
          )}
        </div>
        <ol className="grid gap-5 lg:col-span-8 lg:grid-cols-3 lg:gap-6">
          {events.map((event, index) => (
            <li key={event.field} className="relative border-t border-line pt-4 lg:border-t-2 lg:pt-5">
              <span
                aria-hidden="true"
                className="absolute -top-px left-0 h-px w-8 bg-accent lg:-top-0.5 lg:h-0.5"
              />
              <div className="flex items-baseline gap-3">
                <span className="font-mono text-xs font-medium text-accent">{formatIndex(index + 1)}</span>
                <time dateTime={event.at} className="font-mono text-xs text-ink-2">
                  {formatUtc(event.at, "seconds")}
                </time>
              </div>
              <h4 className="mt-3 text-sm font-semibold leading-snug text-ink">{event.title}</h4>
              <p className="mt-1.5 text-xs leading-5 text-muted">{event.detail}</p>
              <p className="mt-2 font-mono text-[0.6875rem] text-faint">{event.field}</p>
            </li>
          ))}
        </ol>
      </div>
    </div>
  );
}

export function ArtifactIntegrity() {
  const origin = site.url.origin;
  const artifactUrl = `${origin}${demoFile.publicPath}`;
  const verifyShell = `curl -sO ${artifactUrl}\nshasum -a 256 ${demoFile.fileName}`;
  const verifyPowerShell = `curl.exe -sO ${artifactUrl}\nGet-FileHash -Algorithm SHA256 ${demoFile.fileName}`;

  return (
    <Section id="artifacts" labelledBy="artifacts-title">
      <SectionHeading
        index="05"
        kicker="Artifacts"
        title="A frozen record, not a live computation"
        titleId="artifacts-title"
        lead="The displayed result is rendered from a frozen evaluation artifact rather than recomputed in the browser. Both files are published unmodified and can be hashed independently."
      />

      <div className="mt-12 grid gap-6 lg:grid-cols-2">
        <ArtifactFileCard
          file={demoFile}
          title="Evaluation record"
          description="Task identity, attempts, canonical outcomes, evidence references, and the engine narrative."
          badge={
            <StatusBadge tone={integrity.matches ? "success" : "failure"} className="mt-0.5">
              {integrity.matches ? "Verified at build" : "Digest mismatch"}
            </StatusBadge>
          }
        />
        <ArtifactFileCard
          file={freezeFile}
          title="Freeze manifest"
          description="Digest and size of the record, the engine commit that exported it, and three provenance timestamps."
        >
          <LedgerRow label="Artifact created" hint="artifact_created_at">
            {formatUtc(freeze.artifact_created_at, "seconds")}
          </LedgerRow>
          <LedgerRow label="Manifest generated" hint="manifest_generated_at">
            {formatUtc(freeze.manifest_generated_at, "seconds")}
          </LedgerRow>
          {freeze.manifest_corrected_at && (
            <LedgerRow label="Manifest corrected" hint="manifest_corrected_at">
              {formatUtc(freeze.manifest_corrected_at, "seconds")}
            </LedgerRow>
          )}
          <LedgerRow label="Engine commit" hint="demo_implementation_commit">
            <Identifier variant="hash" value={freeze.demo_implementation_commit} label="engine commit" />
          </LedgerRow>
        </ArtifactFileCard>
      </div>

      <ProvenanceTimeline />

      <div className="mt-6 grid gap-6 lg:grid-cols-12">
        <div className="min-w-0 rounded-md border border-line bg-surface p-5 shadow-card sm:p-6 lg:col-span-7">
          <Kicker>Build-time verification</Kicker>
          <h3 className="mt-3 text-lg font-semibold tracking-tight text-ink">The build hashes what it ships.</h3>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            During the production build, the site reads the served copy of{" "}
            <code className="text-[0.8125rem] text-ink-2">{demoFile.fileName}</code>, computes its SHA-256, and
            compares it with the manifest. Any mismatch fails the build. Newlines are normalized to LF by{" "}
            <code className="text-[0.8125rem] text-ink-2">.gitattributes</code>, so the digest is the same on
            every operating system and on the deployment host.
          </p>
          <Ledger className="mt-4 border-t border-line">
            <LedgerRow label="Manifest digest" hint="demo_json_sha256">
              <Identifier variant="hash" value={integrity.claimedSha256} label="manifest digest" />
            </LedgerRow>
            <LedgerRow label="Computed digest" hint="sha256(served bytes)">
              <Identifier variant="hash" value={integrity.computedSha256} label="computed digest" />
            </LedgerRow>
            <LedgerRow label="Size">
              {formatBytes(integrity.computedBytes)}
              {integrity.claimedBytes !== undefined && (
                <span className="text-faint"> · manifest {formatBytes(integrity.claimedBytes)}</span>
              )}
              <span className="text-faint"> · {integrity.newline.toUpperCase()}</span>
            </LedgerRow>
            <LedgerRow label="Result">
              <StatusBadge tone={integrity.matches ? "success" : "failure"}>
                {integrity.matches ? "Digests match" : "Digests differ"}
              </StatusBadge>
            </LedgerRow>
          </Ledger>
        </div>

        <div className="min-w-0 rounded-md border border-line bg-surface p-5 shadow-card sm:p-6 lg:col-span-5">
          <Kicker>Verify it yourself</Kicker>
          <h3 className="mt-3 text-lg font-semibold tracking-tight text-ink">Two commands.</h3>
          <p className="mt-2 text-sm leading-relaxed text-muted">
            Download the record and hash it locally. The digest must equal the manifest value below.
          </p>
          <p className="mt-4 font-mono text-[0.6875rem] uppercase tracking-wider text-faint">macOS / Linux</p>
          <pre className="mt-1.5 whitespace-pre-wrap [overflow-wrap:anywhere] rounded-sm border border-line bg-surface-2 p-3.5 text-xs leading-relaxed text-ink-2">
            <code>{verifyShell}</code>
          </pre>
          <p className="mt-3 font-mono text-[0.6875rem] uppercase tracking-wider text-faint">Windows PowerShell</p>
          <pre className="mt-1.5 whitespace-pre-wrap [overflow-wrap:anywhere] rounded-sm border border-line bg-surface-2 p-3.5 text-xs leading-relaxed text-ink-2">
            <code>{verifyPowerShell}</code>
          </pre>
          <p className="mt-4 text-xs font-medium text-muted">Expected digest</p>
          <div className="mt-1">
            <Identifier variant="hash" value={integrity.claimedSha256} label="expected SHA-256" />
          </div>
        </div>
      </div>

      <details className="group mt-6 rounded-md border border-line bg-surface">
        <summary className="flex items-center justify-between gap-4 rounded-md px-5 py-4 text-sm text-ink">
          <span>
            <span className="font-medium">Preview {demoFile.fileName}</span>
            <span className="text-muted"> — exact bytes as served, {formatBytes(demoFile.bytes)}</span>
          </span>
          <ChevronDownIcon className="shrink-0 text-faint transition-transform group-open:rotate-180" />
        </summary>
        <pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap break-words border-t border-line bg-surface-2 p-5 text-xs leading-relaxed text-ink-2">
          <code>{demoFile.text}</code>
        </pre>
      </details>
    </Section>
  );
}
